### PR TITLE
fix(flattenObject): flatten for nested objects

### LINKED ISSUE #816: flattenObject doesn't handle array of objects
Given this code

```ts
    const result = flattenObject({
      a: [1, { b: 2 }, 3],
    });

    expect(result).toEqual({
      'a.0': 1,
      'a.1.b': 2,
      'a.2': 3,
    });
```

nested object is not flattened 

Screenshot 2024-11-12 at 19 47 16

### PR DESCRIPTION
**Pull request by nnnnoel**
Fixed #816

### CODE REVIEW

File: src/object/flattenObject.ts [hunk 1]
```diff
@@ -46,7 +46,12 @@ function flattenObjectImpl(object: object, prefix = ''): Record<string, any> {
 
     if (Array.isArray(value)) {
       for (let index = 0; index < value.length; index++) {
-        result[`${prefixedKey}.${index}`] = value[index];
+        const valueKey = `${prefixedKey}.${index}`;
+        if (typeof value[index] === 'object' && value[index] !== null) {
```
Comment (nnnnoel) [inline src/object/flattenObject.ts:50]: I think non-object filter needed on top of flattenObjectImpl function, but not sure to code convention of es-toolkit.

Comment (raon0211) [reply src/object/flattenObject.ts]: Actually I think we have a simpler logic here; I made a little modification.

**Review by raon0211 — APPROVED** [review]
Thanks!
